import { createSlice, createEntityAdapter } from "@reduxjs/toolkit";

let initialState = [
  {
    name: "Grilled Burger",
    price: 12,
    ratings: 4,
    src: "./Assets/burger.jpg",
    id: 1,
    category: "burger",
    desc: "Juicy grilled burger with all your favorite toppings.",
  },
  {
    name: "Italian Pizza",
    price: 20,
    ratings: 3,
    src: "./Assets/pizza.jpg",
    id: 2,
    category: "pizza",
    desc: "Delicious Italian-style pizza with fresh ingredients.",
  },
  {
    name: "Grilled Cheese Burger",
    price: 12,
    ratings: 3.5,
    src: "./Assets/cheese-burger.jpg",
    id: 3,
    category: "burger",
    desc: "Classic cheeseburger with gooey melted cheese and grilled beef patty.",
  },
  {
    name: "Pasta",
    price: 10,
    ratings: 4.5,
    src: "./Assets/pasta.jpg",
    id: 4,
    category: "noodles",
    desc: "Satisfying pasta dish with rich tomato sauce and parmesan cheese.",
  },
  {
    name: "Salad",
    price: 3,
    ratings: 0,
    src: "./Assets/salad.jpg",
    id: 5,
    category: "salad",
    desc: "Fresh salad made with crisp lettuce, tomatoes, and cucumbers.",
  },
  {
    name: "Brownie",
    price: 5,
    ratings: 5,
    src: "./Assets/brownie.jpg",
    id: 6,
    category: "desert",
    desc: "Decadent chocolate brownie served warm with a scoop of vanilla ice cream.",
  },
  {
    name: "Ham Burger",
    price: 10,
    ratings: 3,
    src: "./Assets/ham-burger.jpg",
    id: 7,
    category: "burger",
    desc: "Tasty ham burger with a special sauce and crispy lettuce.",
  },
  {
    name: "Steak",
    price: 30,
    ratings: 4,
    src: "./Assets/steak.jpg",
    id: 8,
    category: "meat",
    desc: "Juicy grilled steak cooked to perfection.",
  },
  {
    name: "Chinese Noodles",
    price: 7,
    ratings: 5,
    src: "./Assets/chinese-noodles.jpg",
    id: 9,
    category: "chinese",
    desc: "Authentic Chinese-style noodles with savory sauce and vegetables.",
  },
  {
    name: "macronie",
    price: 7,
    ratings: 2,
    src: "./Assets/macronie.jpg",
    id: 10,
    category: "noodles",
    desc: "Delicious macaroni pasta with creamy cheese sauce.",
  },
  {
    name: "Spicy Tinder Chicken",
    price: 15,
    ratings: 5,
    src: "./Assets/tandori-chicken.jpg",
    id: 11,
    category: "meat",
    desc: "Tender chicken marinated in spicy Tandoori sauce and grilled to perfection.",
  },
  {
    name: "Biryani",
    price: 7,
    ratings: 2,
    src: "./Assets/biryani.jpg",
    id: 12,
    category: "desi",
    desc: "Flavorful rice dish cooked with aromatic spices and tender meat.",
  },
];

let foodSlice = createSlice({
  name: "Food",
  initialState,
  reducers: {},
});
export default foodSlice.reducer;
